package org.processmining.plugins.predictive_monitor.bpm.configuration.data_structure.directory_path_values;
//ask Marco
public class LogFilePath extends Directory_Path_Values{
	public LogFilePath() {
		super();
		
		super.addDefaultValue("LogFilePathStubValue");
		super.setTooltip("Chose where to place the log generated by the software");
	}
}
